### ISSUE TITLE
Routing for Manager Profiles

### ISSUE THREAD

**Issue by andela-ooranagwa** [andela/eventx#116]
The route to `manager_profiles` is defined as `resources` which implies that the *7 Restful Resources* `index`, `show`,  `create`, `new`, `update`, `edit` and `delete` are defined (or managed) in the controller. This currently isn't the case as `new` and `create` are the only actions defined. As it is, a potential error (will) occur if the implied routes are visited.

**Comment by andela-aadepoju** [comment]
This has been fixed.
