### ISSUE TITLE
Create event link is broken online!

### ISSUE THREAD

**Issue by andela-aadepoju** [andela/eventx#154]
The link to create new event throws an error. 
<img width="961" alt="screen shot 2016-05-10 at 3 54 45 pm" src="https://cloud.githubusercontent.com/assets/10416202/15151070/a32ccf04-16c7-11e6-9c50-ac56a3717b28.png">

**Comment by andela-sdamian** [comment]
Alright, the event-x team will look into this and we will definitely do our best to resolve this issue. Thanks @andela-aadepoju  for the attention to detail. 👍
