### ISSUE TITLE
Popular Events and Event Search are not scoped by subdomain

### ISSUE THREAD

**Issue by andela-iokonkwo** [andela/eventx#91]
Content of popular events in the landing page is the same irrespective of whether you are on homepage or on a subdomain. This is as a result of using raw sql in the method defined in the event's model. Take a look at it and include the subdomain in the raw sql.

Also the events shown as search result when searching are also not scoped by subdomain when you are on a subdomain. This is caused by the same reason outlined above.

**Comment by andela-ooranagwa** [comment]
This is a very keen observation. We weren't quick to factor in the exception wherein `act-as-a-tenant` gem doesn't scope queries made using `raw sql`.
This is noted and we'll work to fix it.

**Comment by andela-ooranagwa** [comment]
This has been fix.
